= Arduino and Rust examples
:toc:

## About repository
This repository contains implementation of classical Arduino examples in Rust language using https://github.com/Rahix/avr-hal[avr-hal]

This repository based on tutorials from http://wiki.amperka.ru/%D0%BA%D0%BE%D0%BD%D1%81%D0%BF%D0%B5%D0%BA%D1%82-arduino#%D1%8D%D0%BA%D1%81%D0%BF%D0%B5%D1%80%D0%B8%D0%BC%D0%B5%D0%BD%D1%82%D1%8B[Amperka wiki]. Amperka is Russian's store which sells Arduino kits and extensions. But there is not full implementation of all examples and I changed some of them. I suppose that some examples is too simple or don't give new experience compare to previous.

## How to run on a board

WARNING: I have tested this code only on Linux (Archlinux). It should work on Windows, but you should modify `.cargo/config.toml` (see the instruction in the file). After this you should be generate HEX files manually.

. Plug your Arduino UNO into your PC
. Set enviroment variable with tty of your board. In my setup is usually `/dev/ttyUSB0`:
bash:: ``RAVEDUDE_PORT=/dev/ttyUSB0``
fish:: `set -x RAVEDUDE_PORT /dev/ttyUSB0`
. Run cargo `cargo run --bin <EXAMLPLE_NAME>`,
  for example: `cargo run --bin 01_blink`

TIP: https://fishshell.com/[fish shell] autocompletes examples names.

`cargo run` also generates HEX files, which can be loaded into SimulIDE.

## SimulIDE Projects

Some projects contains https://www.simulide.com/p/home.html[SimulIDE] project (*.sim1) in the folder `simulide`. SimulIDE is a simple real time electronic circuit simulator, intended for hobbyist or students to learn and experiment with simple electronic circuits and microcontrollers, supporting PIC, AVR and Arduino. You can download version for free, if set price to $0.

How to run a project in SimulIDE:

. Open project in SimulIDE
. Right click on Arduino 
. Click "Load firmware" and select <buildname.hex>, which you can find in the folder ``target/avr-atmega328p/debug``

CAUTION: Some projects has simulated in slower mode. I did it for more clarity.

## Examples description

[cols="4h,4,8a,8a,0"]
|===
| Example  | Description | AVR (or Rust) techniques | Arduino functions | SimulIDE

| 01_blink 
| Blinking led - Hello world in the Arduino.  
| * Toggle led 
  * delay milliseconds 
|  `delay` +
   `digitalWrite`
| yes

| 02_blink_fade 
| Led with different brightness 
| Fast PWM mode 
| `analogWrite`
| yes

| 03_pot_light 
| LED with controlled by pot brightness
| ADC, using pot
| `analogRead`
| yes

| 04_buzzer
| Buzzer plays musical notes
| Timer: 

  * compare match mode
  * toggle pin d9 by timer
| `tone`
| yes

| 05_night_light
| LED on/off controlled by pot and photoconductive cell
| ADC, using pot and photoconductive
| `analogRead`
| yes

| 06_pulsar_bar
| Smoothly change brighntess of LED bar
| Fast-Mode PWM with a deep description.
| `analogWrite` +
  `millis`
| yes

| 07_running_bar
| Sequentially on/off leds in a bar
| * AVR-Rust specific - use pins in array. 
  * Working with UART
| `digitalWrite`
| yes

| 09_mixer
| Changes speed of motor by buttons
| pull-up pins
| `pinMode PULLUP` +
  `digitalRead` +
  `digitalWrite`
| yes

| 10_led_toggle
| On/off led by button
| Nothing new compare to 09_mixer
| 
| no

| 11_inc_dec_light
| Change brightness of led with 2 buttons
| External Interrupts (INT0, INT1) 
  Issue with Fast PWM  
| `attachInterrupt`
| no

| 13_seven_segment_counter
| Change digit from 0 to 9 per seconds on 7 segments counter.
| struct as indicator's model
|
| no

| 14_shift_register.rs
| Like 13, but uses 8-bit serial to parallel shift register 74HC595
| SPI
| `shiftOut`
| yes + KiCAD scheme

| 15_display
| Work with LCD 16 symbols 2 row display (HD44780). 

 Example shows an implementation of
  all commands from datasheet.
| Modeling device with `struct` and `impl` (like OOP)
| Implements library `LiquidCrystal`
| Yes

|===